# Generated by Django 5.1.3 on 2024-11-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('deletado', 'Deletado')], default='ativo', max_length=10),
        ),
    ]
