# Generated by Django 5.1.3 on 2024-11-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postagem_conteudo_alter_postagem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='title',
            field=models.CharField(blank=True, default='Sem título', max_length=127, null=True),
        ),
    ]
