# Generated by Django 5.1.3 on 2024-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postagem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/microblog/img/'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
