# Generated by Django 5.1.3 on 2024-11-13 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postagem_imagem_alter_postagem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'O conteúdo deve ter pelo menos 10 caracteres.'), django.core.validators.MaxLengthValidator(255, 'O conteúdo deve ter no máximo 255 carateres.')]),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_expiracao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='title',
            field=models.CharField(max_length=127, validators=[django.core.validators.MinLengthValidator(5, 'O título deve ter pelo menos 5 caracteres.')]),
        ),
    ]
