# Generated by Django 5.1.3 on 2024-11-13 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postagem_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'O conteúdo deve ter pelo menos 10 caracteres.'), django.core.validators.MaxLengthValidator(255, 'O conteúdo deve ter no máximo 255 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_expiracao',
            field=models.DateTimeField(),
        ),
    ]
