# Generated by Django 5.1.3 on 2024-11-25 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postagem_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_expiracao',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 16, 50, 57, 301122, tzinfo=datetime.timezone.utc)),
        ),
    ]
